# Generated by Django 4.0.3 on 2022-04-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_user_modul_druga_zelja_user_modul_prva_zelja_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='modul_druga_zelja',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='modul_prva_zelja',
            field=models.CharField(default='', max_length=50),
        ),
    ]
