# Generated by Django 4.0.3 on 2022-04-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_alter_user_modul_druga_zelja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ostvareni_espb',
            field=models.IntegerField(default=0),
        ),
    ]
