# Generated by Django 4.0.3 on 2022-04-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0006_user_ostvareni_espb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='modul_druga_zelja',
            field=models.CharField(default='Neopredeljen', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='modul_prva_zelja',
            field=models.CharField(default='Neopredeljen', max_length=50),
        ),
    ]
