# Generated by Django 4.0.3 on 2022-05-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0007_alter_user_modul_druga_zelja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='upao_na_drugu_zelju',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='upao_na_prvu_zelju',
            field=models.BooleanField(default=True),
        ),
    ]
