# Generated by Django 4.0.3 on 2022-06-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0008_user_upao_na_drugu_zelju_user_upao_na_prvu_zelju'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
