# Generated by Django 4.0.3 on 2022-05-19 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_modul'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Modul',
        ),
    ]
